### ISSUE TITLE
Check out napi

### ISSUE THREAD

**Issue by Jytesh** [samizdatco/skia-canvas#11]
https://github.com/Jytesh/rust-node-perf

napi supposedly performs better than neon and might be worth checking out as an alternative option to neon

**Comment by Jytesh** [comment]
[This](https://github.com/Brooooooklyn/canvas) is another canvas project using Napi-rs and skia

**Comment by samizdatco** [comment]
I decided to stick with Neon, but have switched over from its legacy bindings to its new N-API interface (see #14). Thanks for the suggestion!
