### ISSUE TITLE
Can this Canvas be converted to raw?

### ISSUE THREAD

**Issue by LmanTW** [samizdatco/skia-canvas#116]
I am using Automattic/node-canvas, I want to change to this canvas, but I tried it and it seems that I can't convert canvas to raw, is there a way to convert canvas to raw?

```js
//in Automattic/node-canvas
canvas.toBuffer('raw')
```

**Comment by vincaslt** [comment]
You can get raw pixel data on context2d (it's rgba order, unglike bgra in node-canvas) and then do whatever you want with it like stream into ffmpeg:

```
const imageData = ctx.getImageData(0, 0, 1080, 1920).data
const buffer = Buffer.from(buffer)
writeFileSync(`out/${frameNum}.raw`, buffer);
```

**Comment by LmanTW** [comment]
It works, thanks for helping!

**Comment by mpaperno** [comment]
However, `getImageData()` is a synchronous operation and will be relatively slow.  [My fork](https://github.com/mpaperno/skia-canvas/blob/mp/main/CHANGELOG.md#--v110-mp--sep-8-2023) has an async option (`toBuffer('raw')`), in case that is useful.   (I'd submit a PR for that, but this project appears to no longer be maintained.)
