### ISSUE TITLE
Support WEBP formats

### ISSUE THREAD

**Issue by n3oney** [samizdatco/skia-canvas#117]
In [PR 417](https://github.com/rust-skia/rust-skia/pull/417), webp support was added to rust-skia, hidden behind feature flags.
Currently, when using loadImage on a webp image, I get a `Could not decode image data` error.  
Could webp support be added to this library, or am I missing some way to load webp images?  
Thank you.

**Comment by meihuanyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by samizdatco** [comment]
Added support in 2.0
