### ISSUE TITLE
Plans for WebGl

### ISSUE THREAD

**Issue by Salmondx** [samizdatco/skia-canvas#15]
Do you have plans to add a support for WebGl to be able to get a webgl context from a canvas?

**Comment by samizdatco** [comment]
I'm not sure that there's much that this project could add to the existing options for using WebGL contexts from Node. From cursory googling it looks like [`headless-gl`](https://github.com/stackgl/headless-gl) covers the render-to-an-image-file use case and [`node-webgl`](https://github.com/mikeseven/node-webgl) provides a WebGL interface for drawing to windows.

One possibility would be for `skia-canvas` to use `headless-gl` as an optional dependency and return one its contexts if the user calls `canvas.getContext("webgl")`, but I'm not sure it'd be worth the complexity vs just using the source package directly. 

Is there something I'm missing that makes using these other packages insufficient (like wanting to use a WebGL canvas in a `drawImage` call to a 2d canvas I suppose)?

**Comment by stepancar** [comment]
We are passing webgl canvas into `drawImage`
