### ISSUE TITLE
How to disable GPU render by default?

### ISSUE THREAD

**Issue by Vandomas** [samizdatco/skia-canvas#181]
When I create canvas with
new Canvas(100,200)

This procedure takes several seconds, with measurements from 1.8 to 2.2 seconds

But I want to speed up this, I think its problem in gpu context initializing.
So I wand disable it
Or I can install new maintenance version 2024?

**Comment by samizdatco** [comment]
fixed in #172

**Comment by Vandomas** [comment]
Very good! It's fixed like fixed speed or added new property to specific engine?
