### ISSUE TITLE
Path2D clipping not affected by scale transformation in skia-canvas

### ISSUE THREAD

**Issue by hlg-facai** [samizdatco/skia-canvas#207]
I have encountered an issue regarding the behavior of Path2D when used with the clip method in skia-canvas. Specifically, it appears that the clipping path defined by Path2D is not affected by the scale transformation applied to the context.

Here is a minimal code example demonstrating the issue:

``` javascript
import { Canvas, Path2D } from 'skia-canvas';
import fs from 'fs';

const canvas = new Canvas(1000, 1000);
const ctx = canvas.getContext('2d');

ctx.scale(2, 2); // Applying scale transformation

const path = new Path2D();
path.rect(0, 0, 500, 500); // Defining a rectangular path

ctx.clip(path); // Clipping using Path2D
ctx.fillStyle = 'red';
ctx.fillRect(0, 0, 500, 500); // Filling a rectangle

fs.writeFileSync('./a.png', canvas.toBufferSync('png'));
```

Expected Behavior:
When using scale, I expect the clipping path to also be affected by this transformation, similar to how it behaves in other environments like browser canvas or node-canvas.

Actual Behavior:
In skia-canvas, the Path2D clipping path does not respect the scale transformation, leading to unexpected results compared to the expected behavior observed in both browser canvas and node-canvas.

Suggested Fix:
It would be beneficial if the clipping behavior for Path2D could be made consistent with other canvas implementations, ensuring that it respects the current transformation state, including scaling.

Environment:
skia-canvas version: v1.0.2
Node.js version: node v20.11.1
Operating System: Mac M1
Thank you for your attention to this matter. I look forward to any updates or fixes regarding this issue.

**Comment by hlg-facai** [comment]
temporary solution

```js
const originClip = CanvasRenderingContext2D.prototype.clip;
CanvasRenderingContext2D.prototype.clip = function clip(path, ...rest) {
    if(path instanceof Path2D) {
        const transform = this.getTransform();
        path = path.transform(transform);
    }
    return originClip.call(this, path, ...rest);
};
```

**Comment by samizdatco** [comment]
Thanks so much for pointing this out! Allowing the Path2D object to be passed to the context's draw functions was a recent addition and in the process I didn't notice the discrepancy between fill/stroke (which applied the canvas's transform matrix) and clip (which didn't). The fix will be in the next release.
