### ISSUE TITLE
installation not working using NPM

### ISSUE THREAD

**Issue by outbackStack** [samizdatco/skia-canvas#21]
Hi Guys,

The installation method `npm install skia-canvas` isn't working. I've tried a couple of times. Has it been published on NPM registry?

**Comment by outbackStack** [comment]
ops my fault! I named my folder as 'skia-canvas' :-)

**Comment by amardeepsingh20** [comment]
So how can we install it then? Unable to install any version after 0.9.19 using npm

**Comment by samizdatco** [comment]
> So how can we install it then? Unable to install any version after 0.9.19 using npm

After 0.9.19 the prebuilt libraries started using S3 hosting rather than GitHub Releases. What kind of errors are you seeing when you try to install? Are they related to not being able to connect to `skia-canvas.s3.us-east-1.amazonaws.com`?

**Comment by amardeepsingh20** [comment]
Correct. Aws url shows access denied. This is specially true on MacOS installs.

**Comment by samizdatco** [comment]
Could you paste in the results you get from running:
```console
npm install --loglevel verbose skia-canvas
```

**Comment by PainOchoco** [comment]
It seems that I have the same error on my Raspberry Pi with Raspbian when I'm trying to install skia-canvas.
Here is the log that I get after running `npm install --loglevel verbose skia-canvas`: https://hastebin.com/upuzuqagux
