### ISSUE TITLE
Inaccurate filter parsing

### ISSUE THREAD

**Issue by PainOchoco** [samizdatco/skia-canvas#23]
Hello there 👋

I was testing the filters on this library (I was previously using node-canvas which doesn't support filters) and I noticed some bugs in the filter parsing.

I made a little app to test the filters differences between skia-canvas and the canvas API:
[skia-canvas_filter_test.zip](https://github.com/samizdatco/skia-canvas/files/6790513/skia-canvas_filter_test.zip)

You can just `npm install` and run `node skia/index.js`, it will generate images in `/skia/images/` using skia-canvas and for the canvas API just open the canvas/index.html file.

The differences are very noticeable when multiple filters are used at once, see the "cyan" filter in `filters.json`. This specific filter is generated from https://codepen.io/sosuke/pen/Pjoqqp using the color `#117676`. 

I hope this issue will help improve skia-canvas,
Thanks!

**Comment by samizdatco** [comment]
It looks like the problem stems from the `saturate(4837%)` step, which is tripping up the css parser's range expectations. Thanks for the report (and the extremely helpful test cases!).
