### ISSUE TITLE
Failed to load icudtl.dat on windows

### ISSUE THREAD

**Issue by thers** [samizdatco/skia-canvas#27]
Attempt to `ctx.fillText` leads to skia error on Windows 10, using Node 16.5.0 (via nvm for windows):
```
SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat.
```

Even tho this file sits right next to native module in `lib/v6`.

**Comment by samizdatco** [comment]
Just to clarify: does it actually fail to draw the text or is it more that it prints out the `datafile missing` message despite running successfully?

**Comment by thers** [comment]
> Just to clarify: does it actually fail to draw the text or is it more that it prints out the `datafile missing` message despite running successfully?

It does fail, no text appear on final image.

**Comment by stalsus** [comment]
yep same issue here, tried master branch and npm version, both produce the same exact error when trying to draw text

**Comment by samizdatco** [comment]
How truly odd. I've been running some tests using a scratch repository and a windows vm and haven't yet been able to reproduce the problem.

The error message **does** get printed to the console:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/469523/126041946-64e75149-0c80-4386-beff-f8f7d9341a8e.png">

But the script continues to run and renders the text just fine:

<img width="512" alt="abc" src="https://user-images.githubusercontent.com/469523/126041966-fba1a666-61b7-4e67-97c4-46e9804a7a59.png">

The [test script](https://github.com/samizdatco/skia-canvas-binaries/blob/331d0e80e109f1ff9cb19b7fcf6c9ade47140649/testtext.js#L1-L9) is simply:

```js
const {Canvas} = require('./lib')
let WIDTH = 512, HEIGHT = 128,
    canvas = new Canvas(WIDTH, HEIGHT),
    ctx = canvas.getContext("2d");

ctx.font = '80px Arial'
ctx.fillText('ABC abc 123', 10, 80)
ctx.fillRect(10, 100, WIDTH-20, 10)
canvas.saveAs('abc.png', {density:2})
```

The job and its output ‘artifact’ can be found [here](https://github.com/samizdatco/skia-canvas-binaries/actions/runs/1040556394). Does anything in the [transcript](https://github.com/samizdatco/skia-canvas-binaries/runs/3093586708?check_suite_focus=true) look different from what you’re getting?

**Comment by stalsus** [comment]
my bad, the text does render fine. where can i get that .dat file to remove the error?

**Comment by samizdatco** [comment]
> my bad, the text does render fine. where can i get that .dat file to remove the error?

That's the frustrating thing: the `.dat` file is actually present (in the `lib/v6` directory), but skia only looks for it there after printing out the error message.

The commit referenced above should make the message go away, but the way it accomplishes this is by generating the `.dat` file in the same directory as your node executable if it's not present. As a result you need to make sure that folder has write-permissions enabled.

There's a [draft PR](https://github.com/rust-skia/rust-skia/pull/486) in rust-skia that will remove the need for a `.dat` file altogether, so with any luck these workarounds will be short-lived...

**Comment by stalsus** [comment]
Glad to hear that! at least its only a windows issue for now.

**Comment by Flicksie** [comment]
This should be reopened as this issue can cause the application to crash/freeze if there are some special unicode characters in the text. See #33
