### ISSUE TITLE
SVG `loadImage`

### ISSUE THREAD

**Issue by Wondermarin** [samizdatco/skia-canvas#32]
Hi!
I understand this is related to #30, but I decided to clarify anyway.

I'm trying to convert `SVG` to `Buffer` and send this to `loadImage`, but I get an error in the output.

_Error_
`Error: Could not decode image data`

_myCode.js_
```js
const svg = `
<svg width="1000" height="250" viewBox="0 0 1000 250" fill="none" xmlns="http://www.w3.org/2000/svg">
    <rect width="1000" height="250" fill="#121212"/>
    <text fill="white" xml:space="preserve" style="white-space: pre" font-family="Roboto" font-size="72" font-weight="bold" letter-spacing="0em"><tspan x="237" y="149.609">TEST</tspan></text>
</svg>
`;

const buffer = Buffer.from(svg);
```

**Comment by samizdatco** [comment]
As you noted, this is because `rust-skia` doesn't yet have the ability to create an image from SVG data. Happily, @triniwiz seems to be making progress on this. Keep an eye on issue #30 for any updates...
