### ISSUE TITLE
Application hangs completely on measureText() when certain characters are in the string.

### ISSUE THREAD

**Issue by Flicksie** [samizdatco/skia-canvas#33]
Running on ubuntu 20.4, node 16.5.0

```js
const {Canvas}=require('skia-canvas');
const canvas = new Canvas(100,100);
const ctx = canvas.getContext('2d');
ctx.measureText("ཻུ۪⸙͎")
```
this will cause the node application to hang at 100% CPU and keep unresponsive indefinitely, no errors, nothing. 
this also happens with other weird unicode but mostly combined characters. 
Since we do support unicode and emojis and a lot of stuff around the unicode range, "blacklisting" some characters not just doesn't seem to cover everything but also might blacklist legitimate uses of combining characters.

If there was some sort of error or operation timeout response to that when it fails it would already be good enough as a temp fix, hanging completely gives no way of mitigating or catching the issue unless we document every character range that can be potentially problematic, which eventually leaves some of them out. 

Our current workaround so far has been having a vanilla node-canvas taking care of the text (which it does just fine with the same text) and then feeding the data-image into skia-canvas. 

**Update:** on windows the following error appears:
`SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat`

**Comment by Flicksie** [comment]
Related: https://github.com/Brooooooklyn/canvas/issues/253

**Comment by samizdatco** [comment]
> Running on ubuntu 20.4, node 16.5.0

So far I haven't been able to replicate the error running your example code in an ubuntu container on my mac. Here's the docker setup I used and the console output from the successful run: https://gist.github.com/samizdatco/6cd8dda30dbfafadbb8dc3c353eb0d6a

Can you think of anything else that might be required to trigger the bug?

> **Update:** on windows the following error appears:
> `SkIcuLoader: datafile missing: C:\Program Files\nodejs\icudtl.dat`

Is there a reason to think this is related to the 100% CPU bug? Your process is hanging on linux, not windows, right?

**Comment by Flicksie** [comment]
> Is there a reason to think this is related to the 100% CPU bug? Your process is hanging on linux, not windows, right?

The same behaviour of  process hanging completely was observed on both, that's why I correlated them. I asked a friend to test on their environment and it turned out to have the same outcome. I tested in two of our machines, one a dedicated and the other one a vps, both behave the same when these unicode characters are seen. Coincidence is not discarded though.

running from docker indeed seems to work. i'll see if i can narrow down what can be causing that. i suspect it could be related to the fonts installed on the system since that's the only thing that seems to be different in the environments. 

I'll investigate further and see if i can provide some more information

**Comment by Flicksie** [comment]
After spending a while installing/uninstalling fonts one by one. turns out the one that causes it to hang is **Segoe UI** 
This may explain why the same thing happens on windows. 
Copying the `segoeui.ttf` file from a C:\Windows\Fonts folder to the machine and `fc-cache -fv` is enough to make it reproductible.

**Comment by Flicksie** [comment]
Other fonts that seem to also trigger this:

DejaVuSans-Oblique
DejaVuSansCondensed-Oblique
DejaVuSans-BoldOblique
DejaVuSansCondensed
DejaVuSansCondensed-Bold
FreeSansOblique

**Comment by samizdatco** [comment]
I updated the `Dockerfile` and `test.js` to use Segoe (presuming the copy I'm linking to is genuine) but it's still not hanging for me:
https://gist.github.com/samizdatco/6cd8dda30dbfafadbb8dc3c353eb0d6a

Have you found a way to reproduce the bug within docker?

**Comment by Flicksie** [comment]
This was honestly very intriguing. After some more testing i finally got it to "not work" on Docker. 
Seems like if Tibetan script support, some fonts (like segoe UI and the ones i listed), and the ancient-fonts package exist all the three of them at the same time, this issue happens. If you comment out any of them this docker will run, but if all three are there, it doesnt. 

That seems like some extreme edge-case situation.

here's the Dockerfile https://gist.github.com/Flicksie/3e3fd6f397f7411e92a17bcaa09ff65e

**Comment by Flicksie** [comment]
I don't know how to sanely test that on windows but given that it comes out of the box with support for pretty much every language out there, this could be why the hanging also happens in it. 

Given how extremely specific this issue is I wouldn't mind if it was marked as wontfix but if we could at least have an error to be handled in the js side it would be good enough

**Comment by samizdatco** [comment]
Are you still encountering this problem? 

I just ran your Docker test from Aug 17th on my Mac with the current (0.9.27) skia-canvas release and it terminated right away with:
```
TextMetrics {
  width: 30.979999542236328,
  actualBoundingBoxLeft: 0,
  actualBoundingBoxRight: 30.979999542236328,
  actualBoundingBoxAscent: 17.265625,
  actualBoundingBoxDescent: 4.015625,
  fontBoundingBoxAscent: 15.310068130493164,
  fontBoundingBoxDescent: 3.8899331092834473,
  emHeightAscent: 15.310068130493164,
  emHeightDescent: 3.8899331092834473,
  hangingBaseline: 12,
  alphabeticBaseline: 0,
  ideographicBaseline: -3.8899331092834473,
  lines: [
    {
      x: 0,
      y: -17.265625,
      width: 30.979999542236328,
      height: 21.28125,
      baseline: 0,
      startIndex: 0,
      endIndex: 16
    }
  ]
}
```

**Comment by samizdatco** [comment]
Presuming then that this has been resolved (though if anyone can find a way to reproduce the hang, please let me know).

**Comment by HinTak** [comment]
Skia on Linux is sensitive to fontconfig (I am coming from skia-python), so it is sensitive to both what fonts you have installed, your fontconfig settings (both system-wide and your personal ones), and values of your LANG and FC_LANG variables.

Maybe the initial person needs to name his values for the last ones.

We found that Chinese locales (`LANG=zh*`) breaks functionality of skparagraph quite badly. Filed upstream.

**Comment by HinTak** [comment]
There seems to be some windows-specific issue with icudtl.dat - in fact that file is only looked-for and that file missing message only on windows.
