### ISSUE TITLE
Hanging and CPU usage goes to 100%

### ISSUE THREAD

**Issue by mjgerace** [samizdatco/skia-canvas#48]
I am using this library with a modified version of https://github.com/adonmo/perspective.ts, in which I've removed references to `document` and made it use the skia-canvas `new Canvas` instead.

For node-canvas, this works great and I get expected results from perspective.ts. However, when using skia-canvas, node's CPU usage goes to 100%. Perspective.ts's `.draw` function finishes executing perfectly, but when I try to use `.toDataUrl`, `.saveImage`, etc, the program just hangs.

There is something that perspective.ts is doing that skia-canvas does not like, and when I try to materialize an image causes this hang.

It's worth noting that without perspective.ts, my calls to `.toDataUrl`, `.saveImage`, etc succeed just fine.

Edit: It seems like skia-canvas _eventually_ gets through. And by eventually, I mean node-canvas takes around 100ms for this operation at most. 2 of my requests with skia took over 2 mins according to `console.time`.

**Comment by mjgerace** [comment]
Any update on tis @samizdatco ?

**Comment by Flicksie** [comment]
this is similar to the situation of #33 
Application hangs and it is completely out of control from userland code. So you can't catch it as an error or detect it or anything. 
A sort of timeout or exception that is returned from the Rust side of things to prevent this from happening in other unforseen situations is badly needed.

**Comment by samizdatco** [comment]
The changes in https://github.com/samizdatco/skia-canvas/commit/6fe3a394ee74c842fb98a3c1652da30c27aa8c45 have sped up perspective.ts significantly in my testing (~4x faster)
