### ISSUE TITLE
Add workaround / check for NaN or zero-sized images

### ISSUE THREAD

**Issue by AlexGustafsson** [samizdatco/skia-canvas#5]
Due to some unfortunate error handling in the main Skia project, if one specifies a canvas with a zero width or height, or a canvas with the width or height being `NaN`, `toBuffer()` will fail with a message like `Unsupported image format: "png"` or `Unsupported file format: "png"`.

I think that it would be in-scope for this project to work around that issue by adding error handling to ensure that the width and height fulfills `typeof x === 'number' && !Number.isNaN(x) && x > 0`.

**Comment by samizdatco** [comment]
It looks like the browser behavior for `NaN` dimensions is to use the default 300 × 150 size for the invalid attribute(s). Setting dimensions to zero seems like something that should be allowed, but the error message when you try to export a file could definitely be improved by explaining it's the size and not the format that's the problem.
