### ISSUE TITLE
putImageData bug

### ISSUE THREAD

**Issue by jeetiss** [samizdatco/skia-canvas#53]
I tested how skia-canvas works and found a bug with `putImageData` (it can be related to #39)

I use skia-canvas to render pdfs with pdf.js This library puts the image data to the canvas in chunks to save JS memory. And that creates a problem.

https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L648-L657

I can reproduce the behavior and here is my repo
- https://github.com/jeetiss/put-image-bug

skia-canvas takes the link to `Uint8ClampedArray` when I put it to `putImageData` after i reuse existing memory modify `Uint8ClampedArray` and put it again to `putImageData`. `skia-canvas` renders two time exact the same `Uint8ClampedArray` (last one).

Thanks for the library, great work!

**Comment by meihuanyu** [comment]
look like gc relationship。

https://github.com/samizdatco/skia-canvas/blob/331db55becb09a5b7bf2e12ef784e6e10fd15c0e/lib/index.js#L393

```
putImageData(imageData, ...coords){  
      setTimeout(() => imageData); 
      this.ƒ('putImageData', imageData, ...coords) 
 } 
```

it work for me。
