### ISSUE TITLE
Drawing an image with globalAlpha set does not make the image transparent

### ISSUE THREAD

**Issue by AlexGustafsson** [samizdatco/skia-canvas#6]
Using `globalAlpha`, one should be able to draw an image onto a canvas with transparency.

Example:

```js
  const canvas = new Canvas(32, 32);
  const ctx = canvas.getContext("2d");
  ctx.fillStyle = 'red';
  ctx.fillRect(0, 0, ctx.canvas.width, ctx.canvas.height);

  const canvas2 = new Canvas(32, 32);
  const ctx2 = canvas2.getContext("2d");
  ctx2.fillStyle = 'blue';
  ctx2.fillRect(0, 0, 15, 15);

  ctx.globalAlpha = 0.5;
  ctx.drawImage(canvas, 0, 0, ctx.canvas.width, ctx.canvas.height);
```

**Comment by samizdatco** [comment]
This is happening specifically when drawing a canvas to another canvas—plain `Image`s do respect the `globalAlpha` setting. 

Currently a `Drawable` is generated from the source canvas, but `draw_drawable` doesn't accept a `Paint` argument specifying the alpha (and I'd also wager that the `globalCompositeOperation` isn't being applied). The solution is probably to use a `Picture` as the intermediate representation, but I'm fuzzy on Skia's distinction between the two and what the possible side effects could be...
