### ISSUE TITLE
Anti-aliasing is inconsistent when drawing a canvas onto another canvas

### ISSUE THREAD

**Issue by EvenTorset** [samizdatco/skia-canvas#77]
Depending on what is done to the canvas that is being drawn onto another, the AA looks different, and it's not consistent with browsers.

Here's a script that demonstrates this by drawing the same simple shape in 6 different ways:
```js
import { Canvas, ImageData, loadImage } from 'skia-canvas'

/*
  All of these functions should do the same thing to the canvas they create,
  cover it with white and clear a square in the center. When saved to a file,
  they all look identical, but when drawn to another canvas, the AA is
  different for each.
*/
const cases = [
  async function() { // Case 1
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Covers the canvas with white and draws a black square in the middle.
      The AA around the outer edge is slightly wrong, and the inner edge
      is missing AA entirely.
    */
    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, 100, 100)
    ctx.clearRect(25, 25, 50, 50)

    return canvas
  },
  async function() { // Case 2
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Same as the first case, except filling a larger rectangle than the canvas
      This makes the AA around the outer edge work like it should do.
    */
    ctx.fillStyle = 'white'
    ctx.fillRect(-50, -50, 200, 200)
    ctx.clearRect(25, 25, 50, 50)

    return canvas
  },
  async function() { // Case 3
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Same as the first case, but extracting the ImageData from it and then
      putting it right back.
      This makes the AA around the outer edge even worse, but does not change
      the inner edge at all.
    */
    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, 100, 100)
    ctx.clearRect(25, 25, 50, 50)
    ctx.putImageData(ctx.getImageData(0, 0, 100, 100), 0, 0)

    return canvas
  },
  async function() { // Case 4
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Same as the first case, but the white is drawn 100 times.
      The more times the white cover is drawn, the more accurate the AA
      becomes. At 100, it seems indistinguishable from the second case.
    */
    ctx.fillStyle = 'white'
    for (let i = 0; i < 100; i++) ctx.fillRect(0, 0, 100, 100)
    ctx.clearRect(25, 25, 50, 50)

    return canvas
  },
  async function() { // Case 5
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Instead of clearing a square in the center, here the white is drawn
      in separate pieces so clearing is not necessary.
      This makes the AA in the center work again, though it is slightly off
      like the outer AA in the first case. It also creates visible seams
      between each piece. 
    */
    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, 100, 25) // Top
    ctx.fillRect(0, 25, 25, 75) // Left
    ctx.fillRect(75, 25, 25, 75) // Right
    ctx.fillRect(25, 75, 50, 25) // Bottom

    return canvas
  },
  async function() { // Case 6
    const canvas = new Canvas(100, 100)
    const ctx = canvas.getContext('2d')

    /*
      Exactly the same as the first case, but returns an image created from the
      canvas instead of the canvas itself.
      This fixes all of the problems and can be used as a workaround for now.
    */
    ctx.fillStyle = 'white'
    ctx.fillRect(0, 0, 100, 100)
    ctx.clearRect(25, 25, 50, 50)

    return loadImage(await canvas.png)
  }
]

const canvas = new Canvas(200 * cases.length, 200)
const ctx = canvas.getContext('2d')

ctx.fillStyle = 'black'
ctx.fillRect(0, 0, canvas.width, canvas.height)

for (const [i, func] of cases.entries()) {
  /*
    Position each canvas differently, and rotate them slightly to make the
    AA visible.
  */
  ctx.resetTransform()
  ctx.translate(100 + i * 200, 100)
  ctx.rotate(0.1)

  ctx.drawImage(await func(), -50, -50, 100, 100)
}

await canvas.saveAs('out.png')
```
This is what the output looks like:
![out](https://user-images.githubusercontent.com/2956956/150672638-61320e64-d516-40a8-9519-53b8a7ac5a7a.png)

The browser equivalent produces 6 identical images: https://jsfiddle.net/f8bLn4ev/
![chrome](https://user-images.githubusercontent.com/2956956/150672645-8ff8f143-aa0f-4a49-9560-5dd584529077.png)

There might be other cases that do equally weird things, this list is most likely not comprehensive. I found this when trying to figure out why a canvas I was drawing didn't get any AA at all, but I wasn't able to reproduce that with just skia-canvas, so that problem might be with something else, but I figured it was also worth mentioning since it might be related.

**Comment by samizdatco** [comment]
This is actually a combination of two issues. The first, addressed by the commit above, was a lack of antialiasing that was specific to the `clearRect` method (now fixed). 

The other factor is something I'm more on the fence about fixing: the standard canvas behavior is to treat the source canvas as a bitmap, whereas I've been allowing them to remain resolution independent up until you call `toBuffer` or `saveAs`. This is why you're seeing those thin 'seams' in Case 5—it's actually drawing the individual rects from the source canvas after applying the destination canvas's transform matrix. This comes in handy in cases where you're changing the scale or orientation; especially when the source canvas contains text, gradients, or the like.

I'm planning to revisit this once [SVG rendering](https://github.com/rust-skia/rust-skia/pull/569) lands in `rust-skia` since it addresses similar use-cases. In the meantime your workaround of converting the source canvas to a bitmap image before drawing it is a good one.

**Comment by EvenTorset** [comment]
> the standard canvas behavior is to treat the source canvas as a bitmap, whereas I've been allowing them to remain resolution independent up until you call `toBuffer` or `saveAs`. 

I can see that being useful in some cases, but wouldn't it be better to move that to its own draw function and stick to the standard for the standard function? Using the workaround is significantly slower than just drawing the canvas normally, I'm guessing that's because it needs to encode and decode a PNG?
